name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm ci
      - run: npm run lint
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm ci
      - run: npm run test
        env:
          PM_USERNAME: ${{ secrets.PM_USERNAME }}
          PM_PASSWORD: ${{ secrets.PM_PASSWORD }}
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: screens
          path: screens/